"""Generate public, source-linked evidence pages for bundled venue profiles."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from researchplot.registry import list_profiles  # noqa: E402

OUTPUT = ROOT / "docs" / "generated" / "profiles"
HEADER = "<!-- Generated by scripts/generate_profile_docs.py; do not edit manually. -->\n\n"


def _profile_page(profile: object) -> str:
    status = getattr(getattr(profile, "status", None), "value", "verified")
    governance = getattr(profile, "governance", None)
    reviewers = getattr(governance, "reviewers", ()) if governance is not None else ()
    maintainers = getattr(governance, "maintainers", ()) if governance is not None else ()
    rows: list[str] = []
    for rule in profile.rules:
        phases = ", ".join(phase.value for phase in rule.phases)
        expected = rule.constraint.value
        if isinstance(expected, tuple):
            expected = ", ".join(str(item) for item in expected)
        unit = f" {rule.constraint.unit}" if rule.constraint.unit else ""
        rows.append(
            f"| `{rule.id}` | {rule.level.value} | {phases} | `{rule.probe}` | "
            f"{rule.constraint.operator.value} `{expected}`{unit} |"
        )
    source_blocks: list[str] = []
    for source in profile.sources:
        digest = getattr(source, "content_sha256", None)
        source_blocks.append(
            f"### {source.title}\n\n"
            f"- Official URL: [{source.url}]({source.url})\n"
            f"- Locator: {source.locator}\n"
            f"- Retrieved: {source.retrieved_on}\n"
            f"- Verified: {source.verified_on}\n"
            f"- Content fingerprint: `{digest or 'not recorded'}`\n"
        )
    caveats = "\n".join(f"- {item}" for item in profile.caveats) or "- None recorded."
    return (
        HEADER
        + f"""# {profile.name}

`{profile.coordinate}` · profile digest `{profile.digest}`

| Property | Value |
| --- | --- |
| Status | `{status}` |
| Venue kind | `{profile.kind.value}` |
| Year | {profile.year or "Rolling guidance"} |
| Verified on | {profile.verified_on} |
| Maintainers | {", ".join(maintainers) or "Not recorded"} |
| Reviewers | {", ".join(reviewers) or "Not recorded"} |

{profile.scope}

## Rules

| Rule ID | Strength | Phases | Probe | Assertion |
| --- | --- | --- | --- | --- |
{chr(10).join(rows)}

## Official sources

{chr(10).join(source_blocks)}

## Caveats

{caveats}

ResearchPlot exposes source-backed evidence and unresolved checks; it does not guarantee
editorial acceptance. Journal-specific instructions override generic publisher guidance.
"""
    )


def generate() -> dict[Path, str]:
    profiles = sorted(list_profiles(), key=lambda item: (item.kind.value, item.id, item.revision))
    generated: dict[Path, str] = {}
    lines = [
        HEADER,
        "# Profile evidence catalog\n\n",
        "Every profile page exposes rule strength, observable phases, official sources, ",
        "verification dates, fingerprints, governance, and caveats.\n\n",
        "| Profile | Kind | Status | Verified | Rules |\n",
        "| --- | --- | --- | --- | --- |\n",
    ]
    for profile in profiles:
        status = getattr(getattr(profile, "status", None), "value", "verified")
        filename = f"{profile.id}.md"
        lines.append(
            f"| [{profile.name}]({filename}) | {profile.kind.value} | `{status}` | "
            f"{profile.verified_on} | {len(profile.rules)} |\n"
        )
        generated[OUTPUT / filename] = _profile_page(profile)
    generated[OUTPUT / "index.md"] = "".join(lines)
    return generated


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = generate()
    stale: list[str] = []
    for path, text in generated.items():
        if args.check:
            if not path.is_file() or path.read_text(encoding="utf-8") != text:
                stale.append(path.relative_to(ROOT).as_posix())
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    existing = set(OUTPUT.glob("*.md")) if OUTPUT.is_dir() else set()
    extras = existing - set(generated)
    if args.check:
        stale.extend(path.relative_to(ROOT).as_posix() for path in sorted(extras))
    else:
        for path in extras:
            path.unlink()
    if stale:
        parser.error("generated profile documentation is stale: " + ", ".join(stale))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
